# Generated by Django 5.2.4 on 2025-07-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_article_category_article_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='readinghistory',
            old_name='read_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown Source', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='multi_articles', to='news.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_news_users', to='news.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
