# Generated by Django 5.0 on 2025-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_summaryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_summary_generated',
            field=models.BooleanField(default=False),
        ),
    ]
